config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :books do
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :reviews, only: [:new, :create, :destroy] do
    resources :votes, only: [:upvote, :downvote] do
      collection do
        post 'upvote'
        post 'downvote'
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :votes, only: [:upvote, :downvote] do
        collection do
          post 'upvote'
          post 'downvote'
        end
      end
    end
  end

  resources :reviews

  resources :users, only: [:show]

  resources :authors, except: [:destroy] do
    resources :books
  end

  resources :results, only: [:index]

  get '/search' => 'search#index'

end

app/views/shared/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name"><h1><%= link_to "Best Reads", books_path %></h1></li>
  </ul>

  <section class="top-bar-section">
  <ul class="left">
        <li class="has-dropdown">
          <%= link_to "Books", books_path %>
          <ul class="dropdown">
            <li class="name"><%= link_to "Add New Book", new_book_path %></li>
            <li class="name"><%= link_to "View All Books", books_path %></li>
          </ul>
        </li>
  </ul>
  <ul class="right">
    <% if user_signed_in? %>
    <li class="name"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li><br>
    <% else %>
      <li class="name"><%= link_to "Sign In", new_user_session_path %></li>
      <li class="name"><%= link_to "Sign Up", new_user_registration_path %></li>
    <% end %>
  </ul>
</section>
</nav>