config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :books do
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :reviews, only: [:new, :create, :destroy] do
    resources :votes, only: [:upvote, :downvote] do
      collection do
        post 'upvote'
        post 'downvote'
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :votes, only: [:upvote, :downvote] do
        collection do
          post 'upvote'
          post 'downvote'
        end
      end
    end
  end

  resources :reviews

  resources :users, only: [:show]

  resources :authors, except: [:destroy] do
    resources :books
  end

  resources :results, only: [:index]

  get '/search' => 'search#index'

end

app/views/layouts/_review.html.erb
<li>
  <div class= 'voting'>
    <% unless current_user.id == review.user.id %>
      <li><%= link_to "Upvote", upvote_review_votes_path(review), class: "upvote", remote: true, method: :post %></li>
      <div id="vote-<%=review.id%>">
        <li><%= review.score %></li>
      </div>
      <li><%= link_to "Downvote", downvote_review_votes_path(review), class: "downvote", remote: true, method: :post %></li>
    <% end %>
  </div>

  <% if params[:controller] == "users" %>
    Review for <%= link_to review.book.title, book_path(review.book) %>:<br>
  <% end %>
  Rating: <%= review.rating %><br>
  <%= review.title %>
  <%= review.body %>
  <% if !(current_user == nil) %>
    <% if review.user == current_user || current_user.admin? %>
      <%= link_to 'Edit', edit_review_path(review), class: 'button small' %>
      <%= button_to 'Delete', { controller: "reviews", action: :destroy, id: review.id }, data: { confirm: "Are you sure?" }, method: :delete %>
    <% end %>
  <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Best Reads</title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="page-wrapper">
    <%= render 'shared/navigation' %>

  <div class="row">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, class: "alert-box #{name} radius" %>
      <% end %>
    <% end %>
  </div>

    <div id="search-bar" class="right">
      <%= form_tag("/search", method: "get") do %>
      <%= text_field_tag :query,
          params[:query],
          placeholder: "Search" %>
      <%= submit_tag "Search", name: nil, class: "submit" %>
      <% end %>
    </div>

    <%= yield %>
    </div>
  </body>
</html>